clc;

global grid

fig = figure('name', 'The Game of Life', ...  
    'menubar','none', ...
    'position',[250 150 800 800], ...
    'numbertitle', 'off', ...
    'KeyPressFcn',@play);
ax = axes(fig, ...
    'units', 'pix', ...
    'Position',[0 0 800 800], ...
    'xlim',[0 40], 'YLim',[0 40], ...
    'XTick',[1:40], 'YTick', [1:40], ...
    'XGrid','on', 'YGrid','on', ...
    'TickLength', [0,0.1], ...
    'NextPLot','add', ...
    'ButtonDownFcn',@click);
grid = zeros(40,40);


function click(ax, ~)
global grid
P = get(ax, 'CurrentPoint');  
X = P(1,1) - mod(P(1,1), 1);
Y = P(1,2) - mod(P(1,2),1);
grid(40 - Y,X+1) = 1
patch([X,X+1,X+1,X], ...
      [Y,Y,Y+1,Y+1], ...
      'red');
end


function getLiveNeighbours(i, j)
neighbourCount = 0;
if i >= 0
    if current(i-1,j) == 1 %check upper
        neighbourCount = neighbourCount + 1;
    end
end

  