% This file contains my method for setting the initial conditions
% graphically via interfacing with the mouse. i had to learn about ui
% components as well as their callback functions, the patch method of
% drawing on an axes and also global variables. i did this in a seperate
% file because i knew that it would be easier to integrate the game engine
% once the gui worked, rather than trying to keep them both working
% simultaneously.

clc;

global c
c = [];

fig = figure('name', 'The Game of Life', ...  
    'menubar','none', ...
    'position',[250 150 800 800], ...
    'numbertitle', 'off');
ax = axes(fig, ...
    'units', 'pix', ...
    'Position',[0 0 800 800], ...
    'xlim',[0 40], 'YLim',[0 40], ...
    'XTick',[1:40], 'YTick', [1:40], ...
    'XGrid','on', 'YGrid','on', ...
    'TickLength', [0,0.1], ...
    'NextPLot','add', ...
    'ButtonDownFcn',@setInit);

function setInit(ax, ~)
global currentGrid c
P = get(ax, 'CurrentPoint');  
X = P(1,1) - mod(P(1,1), 1);
Y = P(1,2) - mod(P(1,2),1);
currentGrid(Y,X) = 1;
c = [c patch([X,X+1,X+1,X], ...
      [Y,Y,Y+1,Y+1], ...
      'black');];
end